version: '3.8'

services:
  payment-service:
    build: .
    container_name: payment-service
    ports:
      - "8083:8083"   # HTTP (Spring Boot)
      - "50053:50053" # gRPC
    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/${POSTGRES_DB:-payment_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-2025}
      GRPC_SERVER_PORT: 50053
      SERVER_PORT: 8083
    depends_on:
      payment-db:
          condition: service_healthy
    networks:
      - payment-service-network
    restart: unless-stopped

  payment-db:
    image: postgres:16-alpine
    container_name: payment-service-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-payment_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-2025}
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - payment-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped
networks:
  payment-service-network:
    driver: bridge

volumes:
  postgres-data:

